spring:
  cloud:
    config:
      enabled: false
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3316/store_3ae_sell?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    use-column-label: true
  mapper-locations: classpath*:store/ae/dao/*.xml
  type-aliases-package: store.ae.entity.pojo
env:
  dev
